### ISSUE TITLE
Jetshoot Error

### ISSUE THREAD

**Issue by RoadPhone** [prefech/JD_logs#16]
When someone shoots the jet, JD logs are posted errors.

![Screenshot_59](https://user-images.githubusercontent.com/92928205/139065818-592f6c8f-c4dd-4e65-8987-5fe326956d61.png)

**Comment by JokeDevil** [comment]
Can you tell me what jet since there are more than one?

**Comment by RoadPhone** [comment]
Only one jet shot. (Several times because of the many errors)

**Comment by Galalalallalalaxyyyy** [comment]
He is asking what the model is. There are multiple jets in the game.

**Comment by RoadPhone** [comment]
Sry, P-996 LAZER

**Comment by JokeDevil** [comment]
Vehicle weapons where added in update V2.0.2
