### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by W0lv3sxD** [prefech/JD_logs#18]
![image](https://user-images.githubusercontent.com/93610323/139915229-6aa90fb8-f1d3-4ea1-8812-2504fe9a5988.png)

This is happening in the console after someone joins the server. I would really appreciate your help in this.

**Comment by Neaw92** [comment]
Same issue as above.

**Comment by JokeDevil** [comment]
@W0lv3sxD @Neaw92 Updating to V2.1.1 should fix this issue.
