### ISSUE TITLE
NOT AN ISSUE BUT AN IDEA!!!!!

### ISSUE THREAD

**Issue by McReeky** [prefech/JD_logs#20]
Hey I really like your script, but could you make or update it so that you can have Kicks and Bans logs aswell.

**Comment by Galalalallalalaxyyyy** [comment]
You can already do that with custom logs.

https://github.com/prefech/JD_logs/wiki

**Comment by McReeky** [comment]
Ok I can connect it how exactly it doesn't really explain it well

**Comment by JokeDevil** [comment]
You can add them with the export.
