### ISSUE TITLE
Update Notice in System Log

### ISSUE THREAD

**Issue by EqiUse79** [prefech/JD_logs#23]
ok, i just downloaded 2.1.4 and installed it yesterday, but no matter what it keeps using the system log channel to push about an update to 2.1.4 and there has been no changes since i downloaded it yesterday but it keeps doing it ?

Any idea's ?

**Comment by JokeDevil** [comment]
Will be looked into.

**Comment by JokeDevil** [comment]
issue has been fixed in the beta. will be patched in the main on the 10e
