### ISSUE TITLE
logs of esx_marker client side script

### ISSUE THREAD

**Issue by mr-capy** [prefech/JD_logs#31]
HOW to make a log of esx_marker in this marker script command registered in client side i am pasting screenshot ..
![Uploading Screenshot (65).png…]()

**Comment by mr-capy** [comment]
local ESX = nil

Citizen.CreateThread(function()
    while ESX == nil do
        TriggerEvent('esx:getSharedObject', function(obj) 
            ESX = obj 
        end)

        Citizen.Wait(0)
    end
end)

RegisterCommand("tpm", function(source)
    TeleportToWaypoint()
end)

TeleportToWaypoint = function()
    ESX.TriggerServerCallback("esx_marker:fetchUserRank", function(playerRank)
        if playerRank == "admin" or playerRank == "superadmin" or playerRank == "mod" then
            local WaypointHandle = GetFirstBlipInfoId(8)

            if DoesBlipExist(WaypointHandle) then
                local waypointCoords = GetBlipInfoIdCoord(WaypointHandle)

                for height = 1, 1000 do
                    SetPedCoordsKeepVehicle(PlayerPedId(), waypointCoords["x"], waypointCoords["y"], height + 0.0)

                    local foundGround, zPos = GetGroundZFor_3dCoord(waypointCoords["x"], waypointCoords["y"], height + 0.0)

                    if foundGround then
                        SetPedCoordsKeepVehicle(PlayerPedId(), waypointCoords["x"], waypointCoords["y"], height + 0.0)
						exports.JD_logs:createLog({
						EmbedMessage = "TPM | "..source..waypointCoords["x"]..","..waypointCoords["y"]..","..height,
						player_id = source,
						channel = "all",
						screenshot = false })
                        break
                    end

                    Citizen.Wait(5)
                end

                ESX.ShowNotification("Teleported.")
            else
                ESX.ShowNotification("Please place your waypoint.")
            end
        else
            ESX.ShowNotification("You do not have rights to do this.")
        end
    end)
end

**Comment by mr-capy** [comment]
i tried to export this way but not working and this code is in client side

**Comment by JokeDevil** [comment]
Join our discord for support.
https://discord.gg/prefech
