### ISSUE TITLE
[BUG] native bug

### ISSUE THREAD

**Issue by ViolentMinds** [prefech/JD_logs#35]
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[      script:JD_logs] SCRIPT ERROR: Execution of native 00000000406b4b20 in script host failed: Argument at index 0 was null.

After the latest update I have this bug in console

**Comment by LeonNRL** [comment]
iI have this problme too and i have this error:
[      script:JD_logs] SCRIPT ERROR: @JD_logs/server/functions.lua:349: attempt to concatenate a nil value
[      script:JD_logs] > CreateLog (@JD_logs/server/functions.lua:349)
[      script:JD_logs] > CreateLog (@JD_logs/server/functions.lua:436)
[      script:JD_logs] > handler (@JD_logs/server/server.lua:242)
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[      script:JD_logs] SCRIPT ERROR: Execution of native 00000000406b4b20 in script host failed: Argument at index 0 was null.

**Comment by JokeDevil** [comment]
patched in the hotfix
