### ISSUE TITLE
[error] 'Register Command'

### ISSUE THREAD

**Issue by GERShox** [prefech/JD_logs#36]
[ citizen-server-impl] Stopping resource smx_discord
[    c-scripting-core] Creating script environments for smx_discord
[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[  script:smx_discord] Error loading script server/server.lua in resource smx_discord: Execution of native 000000005fa79b0f in script host failed: Argument at index 1 was null.
[  script:smx_discord] stack traceback:
[  script:smx_discord] 	[C]: in upvalue '_in'
[  script:smx_discord] 	citizen:/scripting/lua/natives_server.lua:1249: in function 'RegisterCommand'
[  script:smx_discord] 	@smx_discord/server/server.lua:370: in main chunk
[    c-scripting-core] Failed to load script server/server.lua.

**Comment by JokeDevil** [comment]
Issue in your config. Open a ticket on our discord for support.
