### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by daveayee** [prefech/JD_logs#37]
Not an issue but a suggestion.

For a while, players kept getting kicked for "reliable network overflow" when using the jerrycan when pouring petrol...
 
 When using the jerrycan it gets logged in shooting logs, but when you open the `netEventLog` you see the logs getting completely flooded and spammed which causes players to disconnect due to  "reliable network overflow"
 
It's not hard for anyone to add `weapon_petrolcan` to the "WeaponsNotLogged"  but I am just suggesting to maybe have it included by default to prevent it from happening to others.

Cheers.

**Comment by JokeDevil** [comment]
Will be added next patch.

**Comment by JokeDevil** [comment]
Implemented
