### ISSUE TITLE
After updating JD_logs, this error appears

### ISSUE THREAD

**Issue by mcNuggets1** [prefech/JD_logs#42]
https://i.imgur.com/CskiJFD.png

**Comment by Maureks** [comment]
mine does not work anymore too !

**Comment by JokeDevil** [comment]
Can you give some more details on your issue?

**Comment by stricktech** [comment]
haveing same, very similar issue, tried to update and started getting these errors, even tried to go back to previous version, still getting error
![jdlogerror](https://user-images.githubusercontent.com/50678364/153634564-c679f8ac-af40-4731-8392-887fbb8b1af8.png)
s

**Comment by JokeDevil** [comment]
@stricktech You just made a typo in your webhooks file.

**Comment by stricktech** [comment]
I will re-download new version and set up again, and send send results. I'm fairly certain there's no mistakes. As it was all copy paste from previous log.

Also, unless I turn global ban status to false, it hangs on it indefinitely when trying to join server.

**Comment by JokeDevil** [comment]
@stricktech Make a ticket on our discord or open your own issue

**Comment by JokeDevil** [comment]
@mcNuggets1 Fixed for next patch
