### ISSUE TITLE
errors after updateing

### ISSUE THREAD

**Issue by stricktech** [prefech/JD_logs#45]
after updateing to JD_logs 2.1.7.7 i get a string of errors in console, i have triple checked the webhook file (only file edited) and all webhooks are correct and inbetween there " " , i have even tried to go back to previous version and still receive some form of errors. Also unless i turn off global ban checking or stop JD_logs, when trying to join server you get stuck by jd_logs global ban check indefinitely.

with JD_logs not set to start on startup, console receives no errors.

![jdlogerror](https://user-images.githubusercontent.com/50678364/153639897-1880a1ee-bb83-4ab6-87f7-6d1c260e2ece.png)

**Comment by stricktech** [comment]
if manually stoping and starting JD_logs, this is the error in consol
![jdlogerr2](https://user-images.githubusercontent.com/50678364/153641999-8557ba77-0f25-4b90-b41b-6c43fca254ab.png)
e

**Comment by JokeDevil** [comment]
Not a bug.

**Comment by mcNuggets1** [comment]
If this is not a bug, what is it then?
It happens, when someone connects and disconnects in the process before fully authing to the server.
