### ISSUE TITLE
Death log

### ISSUE THREAD

**Issue by Nodi007** [prefech/JD_logs#9]
Hello. After last update I dont get player death reason. It just says "he died" not who killed him or why he died... (on the picture its compared old vs new...)

![image](https://user-images.githubusercontent.com/82405303/114436838-1dc1c480-9bc6-11eb-90d4-cc3a0cf32042.png)

**Comment by DmACKGL** [comment]
Same issue

**Comment by JokeDevil** [comment]
https://prefech.com/discord
